# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8900b42a71181997912e6c88b33fd8f63f3789aebcf2c5bd35d9af89ff00a624e448028a10894a4d2e73543e884ecf9d6bf9f83da655cf304da0329ead53c67

test:
  secret_key_base: b6c30d95d79bef5d69f8b5353c567c97abe480283a501f642f0ac4ada7f25c19f7a8a78be9e8b2fa157bdb39e501a84e4138f5fd3bba70ac82477b170ad28712

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
